# Используем легкий образ Python
FROM python:3.13-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файл зависимостей
COPY requirements.txt .

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем остальной код
COPY . .

# Открываем порт
EXPOSE 8000

# Команда запуска (укажи свой путь к main.py)
CMD ["uvicorn", "application.api.main:app", "--host", "0.0.0.0", "--port", "8000"]